# -*- coding: utf-8 -*-
"""AI Government Scheme Recommender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bm8rttxpn-Y2RxDjO_7y2tLeyY-ZAL4G

**AI Government Scheme Recommender**

---

**1. Setup & Installation**
"""

!pip install -U google-genai

"""**2. Gemini API Initialization**"""

from google import genai

client = genai.Client(api_key="Private-Key")

"""**3. Schemes Data & Rules**"""

schemes = [
    {
        "name": "PMAY (Pradhan Mantri Awas Yojana)",
        "condition": lambda u: u["income"] < 300000,
        "benefits": "Affordable housing for low-income families",
        "documents": ["Aadhaar Card", "Income Certificate", "Bank Details"],
        "steps": [
            "Visit PMAY website",
            "Fill application form",
            "Upload documents",
            "Submit"
        ],
        "link": "https://pmaymis.gov.in/"
    },
    {
        "name": "NSP Scholarship",
        "condition": lambda u: u["occupation"] == "student" and u["income"] < 250000,
        "benefits": "Financial support for students",
        "documents": ["Aadhaar", "Income Certificate", "Student ID"],
        "steps": [
            "Go to NSP portal",
            "Register",
            "Fill form",
            "Submit"
        ],
        "link": "https://scholarships.gov.in/"
    },
    {
        "name": "Ayushman Bharat",
        "condition": lambda u: u["income"] < 200000,
        "benefits": "Free health insurance up to ₹5 lakh",
        "documents": ["Aadhaar", "Ration Card"],
        "steps": [
            "Check eligibility",
            "Visit hospital",
            "Get treatment"
        ],
        "link": "https://pmjay.gov.in/"
    },
    {
        "name": "PM Kisan",
        "condition": lambda u: u["occupation"] == "farmer",
        "benefits": "₹6000/year financial support",
        "documents": ["Land Records", "Aadhaar"],
        "steps": [
            "Register online",
            "Verify documents",
            "Receive benefits"
        ],
        "link": "https://pmkisan.gov.in/"
    }
]

"""**4. User Input Collection**"""

user = {}

user["name"] = input("Enter your name: ")
user["age"] = int(input("Enter your age: "))
user["gender"] = input("Enter your gender: ").lower()
user["income"] = int(input("Enter your annual income (₹): "))
user["occupation"] = input("Enter occupation: ").strip().lower()
user["category"] = input("Enter category: ").strip().upper()
user["state"] = input("Enter state: ").strip().lower()
user["locality"] = input("Enter locality: ").strip().lower()

print("\n✅ User Profile:")
print(user)

"""**5. AI Explanation Module**"""

def get_reason(user, scheme_name):
    prompt = f"""
    User Details:
    {user}

    Explain in one short line why this user is eligible for {scheme_name}.
    """

    response = client.models.generate_content(
        model="gemini-1.5-flash",
        contents=prompt
    )

    return response.text.strip()

"""**6. Eligibility Engine**"""

def check_eligibility(user, schemes):
    results = []

    for scheme in schemes:
        print(f"\n🔍 Checking: {scheme['name']}")

        try:
            cond = scheme["condition"](user)
            print("Condition result:", cond)

            if cond:
                print("✅ MATCHED")

                results.append({
                    "scheme_name": scheme["name"],
                    "eligibility_reason": "Matched based on your profile",
                    "benefits": scheme["benefits"],
                    "documents": scheme["documents"],
                    "steps": scheme["steps"],
                    "link": scheme["link"]
                })
            else:
                print("❌ Not matched")

        except Exception as e:
            print("⚠️ Error:", e)

    return results

"""**7. Results & Recommendations**"""

results = check_eligibility(user, schemes)

if results:
    print("\n🎯 Recommended Schemes:\n")

    for r in results:
        print("===================================")
        print("📌 Scheme:", r["scheme_name"])
        print("✅ Why Eligible:", r["eligibility_reason"])
        print("💰 Benefits:", r["benefits"])
        print("📄 Documents:", ", ".join(r["documents"]))

        print("📝 Steps:")
        for step in r["steps"]:
            print(" -", step)

        print("🔗 Apply:", r["link"])
else:
    print("❌ No matching schemes found.")